### Create a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email":"saty@test.com",
    "username":"saty",
    "password":"123456"
}


### sign in a user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "username":"mahi",
    "password":"123456"
}


### Find a particular user with given ID
GET http://localhost:3000/auth/610e2c1758b5ae1c88e7b0b5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMGUyYzE3NThiNWFlMWM4OGU3YjBiNSIsImlhdCI6MTYyODM0MTE2NiwiZXhwIjoxNjI4MzQxMTY3fQ.KkpbtcxtINTlVGOKOTdmTiG6k_AUho8K4oKL-yAQtfM
### Delete a particular user with given ID
DELETE http://localhost:3000/auth/610da939be606f4e946bc155


### Update a particular user with given ID
PATCH http://localhost:3000/auth/610e2c1758b5ae1c88e7b0b5
Content-Type: application/json

{
    "password":"123456"
}

### Signout a user
POST http://localhost:3000/auth/signout
